project_id = "dteppsfseusqixuppglh"

[functions.download-media]
verify_jwt = false

[functions.webhook-conversas]
verify_jwt = false

[functions.webhook-meta]
verify_jwt = false

[functions.webhook-leadgen]
verify_jwt = false

[functions.api-funil-vendas]
verify_jwt = true

[functions.api-tarefas]
verify_jwt = true

[functions.api-waze-agenda]
verify_jwt = false

[functions.enviar-whatsapp]
verify_jwt = true

[functions.enviar-whatsapp-meta]
verify_jwt = true

[functions.transcrever-audio]
verify_jwt = true

[functions.executar-fluxo]
verify_jwt = true

[functions.ia-atendimento]
verify_jwt = true

[functions.ia-vendedora]
verify_jwt = true

[functions.ia-suporte]
verify_jwt = true

[functions.ia-aprendizado]
verify_jwt = true

[functions.enviar-credenciais-subconta]
verify_jwt = true

[functions.redefinir-senha-subconta]
verify_jwt = true

[functions.criar-usuario-subconta]
verify_jwt = true

[functions.elevate-super-admin]
verify_jwt = true

[functions.super-admin-login]
verify_jwt = false

[functions.corrigir-texto]
verify_jwt = true

[functions.ia-analise-comercial]
verify_jwt = false

[functions.asaas-api]
verify_jwt = false

[functions.meta-marketing-insights]
verify_jwt = false

[functions.fetch-whatsapp-messages]
verify_jwt = true

[functions.batch-profile-pictures]
verify_jwt = true

[functions.evolution-create-instance]
verify_jwt = false

[functions.configure-webhook]
verify_jwt = false

[functions.nvoip-call]
verify_jwt = true

[functions.cleanup-storage]
verify_jwt = true

[functions.cleanup-database]
verify_jwt = true

[functions.disparo-em-massa]
verify_jwt = false

[functions.gerar-conteudo-site]
verify_jwt = true
